travis:
  secure:
    BINSTAR_TOKEN: iBuLaaNYyGTnLfGeI33pLibQicJ4wkS3siCdz6ulzOgKD6X//TW4pdGV+u2Qbw7hQzCX894JIel5kVShhxDJEH6a/vIQmH6m+zixgMoj95HKaWB7AG2Px7vF0sebdxw+oybIJNNaSo3XbCPoFwY6MZKmjMZdfyB1rtyhHxHRwI6Pik54aT2Vcs87x18uEj2csfnsdqCTG7DsCklniGlhIBtnDW/rY68f2oAkSHaCl2uDe2pyyeTjqln9YRXiNtfKSmWZ30AbN2vE9CC1tv7RQQ8xBI/lG99DyRMczev6kNW7F06lt66+HDJ2ZdMvKeQHujz2ydKbS2mVpBSsDVU0P5u9nLOPuL+mxud1prPezTwJGPDE2eptqptwvcl6/VTvm+Jh5yftFoML8kL2g0rBaXyBFH22XDTMCiZPiZBB1JgFLahdmHeCXQ7AcTrOmAgh/YkB29Bhy6lQdR+AXfz08tbqGlTS1h6E7PmrSNqkSPRTfqpRZO126LjuaAfz1rstDHqhyeT4dN16UF2t3dZBc3wKdjolkhBWB2n8P5r//yjpAEOuIqSFBG86QM8EKPI1HLZTzFbmiqCmVLRy7Ei36kmb1MQiPxJOYUbxsG0t4CL3a6p3lSr1CxJKxsX1n8mmEvuqBuEZbGBDaZVq1PKb+PAzUGr8/hLtFfq4VffRTyY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
